### ISSUE TITLE
Full node - Block download no longer increases

### ISSUE THREAD

**Issue by davjack** [thetatoken/theta-protocol-ledger#171]
In order to have access to all the data of the Theta blockchain locally without going through an intermediary, I've been downloading the entire Theta blockchain through theta-protocol-ledger (on an Ubuntu Server in version 3.2.0) for several months now.

It was working well, but suddenly the number of blocks did not increase anymore. It remains frozen on the block 11217793 ("current_height" increases well and matches the block displayed on https://explorer.thetatoken.org/ but "latest_finalized_block_height" does not increase anymore.). I have to say that I didn't do anything before the problem occurred (I upgraded to version 3.2.0, the day of the announcement, so well before the problem appeared). Also, this is the second time this has happened to me. The first time, I decided to start again from scratch the installation of my full node, but apparently without success.

Unfortunately, I can't find a solution to my problem in the ThetaLabs documentation or on the Github of the application.
I use the Genesis Snapshot for my fullnode (downloaded here: https://github.com/thetatoken/theta-protocol-ledger/tree/master/integration/mainnet/walletnode ) and the content of my configuration file config.yaml is as follows:
```
# Theta mainnet guardian configuration
storage:
  statePruningEnabled: false
p2p:
  opt: 0
  port: 30002
  seeds: 18.217.234.19:21000,3.16.9.73:21000,3.20.109.241:21000,18.223.165.134:21000,35.184.232.41:21000,35.230.172.8:21000,34.83.20>
  minNumPeers: 24
  maxNumPeers: 96
  natMapping: true
rpc:
  port: 16888
  enabled: true
  maxConnection: 5
log:
  levels: "*:info,guardian:debug"`
```

Is this problem known (perhaps a corrupted downloaded block)?

And if it is known, is there a way to solve the problem without starting the download all over again?
